### ISSUE TITLE
Notes don't match code. 

### ISSUE THREAD

**Issue by aaaaathatsfiveas** [holdena12/wordle#1]
https://github.com/holdena12/wordle/blob/660ebf33ff1784ae4430ed94c37d1278ad31b93c/wordle.py#L40

Notes say program will print 1 if character is in answer AND correct spot, but it actually prints 2 instead.  (And vice versa for character in answer and not in correct spot.) 

Great program!

**Comment by holdena12** [comment]
Thanks, we fixed it and added an easy mode.

**Comment by holdena12** [comment]
fixed
